### ISSUE TITLE
Argument validation runs before converting to uppercase

### ISSUE THREAD

**Issue by deosrc** [kappa7194/base32#2]
The `Decode` method converts the input string to uppercase, but it runs the validation to ensure the characters are valid first. This means that the character check is case sensitive.

I've got a fix ready which should resolve it and maintain backwards compatibility. PR is on it's way.

**Comment by kappa7194** [comment]
Thanks for the suggestion, however I opted to transparently allow case-independent decoding, the user shouldn't be burdened with specifying if it's passing lowercase or uppercase characters, since both of them are valid.
